version: '3.0'
services:
  livraria:
    build: ..
    ports: 
      - 8080:8080
    volumes:
      - ../logs:/logs  
  db:
    image: postgres
    restart: always
    hostname: dblivraria
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=livraria