version: '3.0'
services:
  db:
    image: postgres
    restart: always
    hostname: dblivraria
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin